export { NeuralMesh } from './NeuralMesh.js'
export { checkCapabilities, printStartupBanner, warnIfUnavailable } from './agent/CapabilityChecker.js'
export type { Capabilities, CapabilityReport, MissingCapability } from './agent/CapabilityChecker.js'
export { Agent } from './agent/Agent.js'
export type { NeuralMeshConfig, AgentHandle, ServiceHandler } from './agent/AgentConfig.js'
export type { AgentState } from './agent/AgentState.js'
export { ENSResolver } from './discovery/ENSResolver.js'
export { AXLClient } from './mesh/AXLClient.js'
export { GossipSub } from './mesh/GossipSub.js'
export { Convergecast } from './mesh/Convergecast.js'
export { LocalStore } from './memory/LocalStore.js'
export { TrainingBuffer } from './memory/TrainingBuffer.js'
export { Compute } from './intelligence/Compute.js'
export { KeeperHub } from './execution/KeeperHub.js'
export { AgenticWallet } from './execution/AgenticWallet.js'
export { EvolutionLoop } from './evolution/EvolutionLoop.js'
