/**
 * Evolution Agent — Configuration
 *
 * ┌─────────────────────────────────────────────────────────────┐
 * │  WHAT IS THE EVOLUTION AGENT?                               │
 * │                                                             │
 * │  The Evolution agent is the "training director".            │
 * │  It watches all other agents, waits until they've done      │
 * │  enough tasks to learn from, then triggers AI fine-tuning   │
 * │  using 0G's infrastructure.                                 │
 * │                                                             │
 * │  The result: agents improve automatically without YOU       │
 * │  doing anything. They literally get smarter on their own.   │
 * │                                                             │
 * │  After each training run, the new model weights are stored  │
 * │  as an iNFT on the 0G Galileo chain — so the agent OWNS    │
 * │  its own intelligence. That's the ERC-7857 standard.        │
 * └─────────────────────────────────────────────────────────────┘
 *
 * HOW DOES THE EVOLUTION LOOP WORK?
 *   Step 1: Researcher completes 50 tasks → training buffer fills
 *   Step 2: TrainingBuffer calls back → Evolution agent wakes up
 *   Step 3: Evolution exports task history from 0G Storage as JSONL
 *   Step 4: Sends fine-tuning job to 0G Compute (ZG_FINETUNE_PROVIDER)
 *   Step 5: Gets back a LoRA adapter (small AI improvement patch)
 *   Step 6: Mints the adapter as an iNFT — onchain proof of upgrade
 *   Step 7: Gossips the new adapter hash to all agents via AXL
 *   Step 8: Agents load the new adapter → immediately smarter
 *
 * WHAT IS A LoRA ADAPTER?
 *   Instead of retraining the whole AI model (expensive), we create a
 *   small "patch" that adjusts specific behaviors. It's like a software
 *   hotfix for the AI brain — fast, cheap, targeted.
 *
 * WHAT DO YOU NEED TO ENABLE EVOLUTION?
 *   - ZG_FINETUNE_PROVIDER in .env (your 0G fine-tuning node address)
 *   - PRIVATE_KEY in .env (to mint the iNFT after training)
 *   - INFT_CONTRACT in .env (where to mint the intelligence NFT)
 *   Without these, evolution is silently skipped — agents still work,
 *   they just don't self-improve automatically.
 *
 * WHERE DOES IT RUN?
 *   Locally on your machine, port 9042. Logs: logs/evolution.log
 */
export const config = {
  // ── Identity ──────────────────────────────────────────────────────────────
  // The evolution agent's ENS name. Agents gossip "evolution is ready"
  // messages to this address after training thresholds are hit.
  ensName: process.env['EVOLUTION_ENS'] ?? 'evolution.neuralmesh.eth',

  // ── AXL P2P Network Ports ─────────────────────────────────────────────────
  // Port 9042 = the HTTP port for sending evolution trigger messages.
  // This is typically called automatically by the TrainingBuffer, not by you.
  axlApiPort: parseInt(process.env['EVOLUTION_AXL_API_PORT'] ?? '9042', 10),

  // ── AXL Identity Key ──────────────────────────────────────────────────────
  // The evolution agent's unique cryptographic key on the AXL mesh.
  // Generated by `pnpm keys` — one command creates keys for all 5 agents.
  axlKeyPath: process.env['EVOLUTION_AXL_KEY_PATH'] ?? './packages/agents/shared/axl-keys/evolution.pem',

  // ── AI Model ──────────────────────────────────────────────────────────────
  // Qwen 2.5 7B is used for meta-reasoning: "is this training data good?
  // should we trigger evolution now? what's the quality threshold?"
  model: 'qwen/qwen-2.5-7b-instruct',

  // ── Capabilities ──────────────────────────────────────────────────────────
  //   evolve  — trigger and manage fine-tuning jobs on 0G Compute
  //   monitor — watch training buffers and task counts across all agents
  //   upgrade — distribute new LoRA adapters to agents via AXL gossip
  capabilities: ['evolve', 'monitor', 'upgrade'],
}
