// Command axl-agent manages the AXL subprocess lifecycle for NeuralMesh agents.
//
// It:
//  1. Loads and validates configuration from environment variables.
//  2. Writes an AXL YAML config file to a temp directory.
//  3. Spawns the AXL binary (must be in PATH) with that config.
//  4. Waits for AXL to be ready by polling /api/self with a timeout.
//  5. Prints "READY:<pubkey>" to stdout (TypeScript parent waits for this line).
//  6. Forwards OS signals (SIGINT, SIGTERM) to the AXL process.
//  7. Blocks until the AXL process exits, then exits with the same code.
//
// Environment variables (see internal/config for full docs):
//
//	AXL_API_PORT    — HTTP bridge port (default: 9002)
//	AXL_TCP_PORT    — Yggdrasil internal port (default: 7000)
//	AXL_KEY_PATH    — path to ed25519 PEM key (required)
//	AXL_BRIDGE_ADDR — bind address (default: 127.0.0.1, MUST stay 127.0.0.1)
//	AGENT_NAME      — human label (default: "agent")
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"syscall"
	"text/template"
	"time"

	"github.com/neuralmesh/axl-go/internal/config"
)

// axlConfigTemplate is the YAML config written to disk for the AXL subprocess.
// TCPPort is the Yggdrasil internal P2P port — app code NEVER touches it.
// BridgeAddr:APIPort is the HTTP API endpoint that all app code uses.
const axlConfigTemplate = `# AXL config generated by axl-agent for agent "{{.AgentName}}"
# DO NOT EDIT — this file is regenerated on every start.
peers: []
listen_tcp: ":{{.TCPPort}}"
bridge_addr: "{{.BridgeAddr}}:{{.APIPort}}"
private_key_file: "{{.KeyPath}}"
`

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "[axl-agent] fatal: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	// ── 1. Load config from environment ──────────────────────────────────────
	cfg, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}

	// ── 2. Validate config (hard-rejects non-127.0.0.1 bridge addr) ──────────
	if err := cfg.Validate(); err != nil {
		return fmt.Errorf("invalid config: %w", err)
	}

	fmt.Fprintf(os.Stderr, "[axl-agent] agent=%s api_port=%d tcp_port=%d key=%s\n",
		cfg.AgentName, cfg.APIPort, cfg.TCPPort, cfg.KeyPath)

	// ── 3. Write AXL YAML config to a temp file ───────────────────────────────
	tmpDir, err := os.MkdirTemp("", fmt.Sprintf("axl-agent-%s-*", cfg.AgentName))
	if err != nil {
		return fmt.Errorf("creating temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	cfgPath := filepath.Join(tmpDir, "axl-config.yaml")
	if err := writeAXLConfig(cfgPath, cfg); err != nil {
		return fmt.Errorf("writing AXL config: %w", err)
	}
	fmt.Fprintf(os.Stderr, "[axl-agent] wrote AXL config to %s\n", cfgPath)

	// ── 4. Spawn AXL binary ───────────────────────────────────────────────────
	axlBin, err := exec.LookPath("axl")
	if err != nil {
		return fmt.Errorf(
			"axl binary not found in PATH — download from https://github.com/gensyn-ai/axl/releases "+
				"and ensure it is executable: %w", err,
		)
	}

	axlCmd := exec.Command(axlBin, "--config", cfgPath)
	axlCmd.Stdout = os.Stderr // AXL logs go to our stderr so TypeScript parent only sees READY: on stdout
	axlCmd.Stderr = os.Stderr

	if err := axlCmd.Start(); err != nil {
		return fmt.Errorf("starting AXL process: %w", err)
	}
	fmt.Fprintf(os.Stderr, "[axl-agent] AXL started (pid %d)\n", axlCmd.Process.Pid)

	// ── 5. Wait for AXL to be ready ───────────────────────────────────────────
	selfInfo, err := waitForReady(cfg.APIPort, 30*time.Second)
	if err != nil {
		// AXL failed to start — kill it and bail.
		axlCmd.Process.Kill()
		axlCmd.Wait()
		return fmt.Errorf("AXL did not become ready within 30s: %w", err)
	}

	// ── 6. Signal readiness to TypeScript parent ──────────────────────────────
	// TypeScript side waits for a line matching /^READY:/ on stdout.
	fmt.Printf("READY:%s\n", selfInfo.Pubkey)
	fmt.Fprintf(os.Stderr, "[axl-agent] ready — pubkey=%s address=%s\n",
		selfInfo.Pubkey, selfInfo.Address)

	// ── 7. Forward OS signals to AXL ─────────────────────────────────────────
	sigCh := make(chan os.Signal, 4)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM, syscall.SIGHUP)
	go func() {
		for sig := range sigCh {
			fmt.Fprintf(os.Stderr, "[axl-agent] forwarding signal %s to AXL\n", sig)
			axlCmd.Process.Signal(sig)
		}
	}()

	// ── 8. Block until AXL exits ──────────────────────────────────────────────
	state, err := axlCmd.Wait()
	signal.Stop(sigCh)
	close(sigCh)

	if err != nil {
		// If the process exited with a non-zero code, err wraps *ExitError.
		// We still want to propagate the exit code.
		if exitErr, ok := err.(*exec.ExitError); ok {
			code := exitErr.ExitCode()
			fmt.Fprintf(os.Stderr, "[axl-agent] AXL exited with code %d\n", code)
			os.Exit(code)
		}
		return fmt.Errorf("waiting for AXL: %w", err)
	}

	fmt.Fprintf(os.Stderr, "[axl-agent] AXL exited cleanly (code %d)\n", state.ExitCode())
	return nil
}

// writeAXLConfig renders the YAML template and writes it to path.
func writeAXLConfig(path string, cfg *config.AXLConfig) error {
	tmpl, err := template.New("axl-cfg").Parse(axlConfigTemplate)
	if err != nil {
		return fmt.Errorf("parsing config template: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating config file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, cfg); err != nil {
		return fmt.Errorf("rendering config template: %w", err)
	}
	return nil
}

// selfResponse matches the JSON returned by AXL /api/self.
type selfResponse struct {
	Pubkey  string `json:"pubkey"`
	Address string `json:"address"`
}

// waitForReady polls AXL's /api/self endpoint until it responds successfully or timeout elapses.
// It returns the node's own SelfInfo so we can print the pubkey to stdout.
func waitForReady(apiPort int, timeout time.Duration) (*selfResponse, error) {
	url := fmt.Sprintf("http://127.0.0.1:%d/api/self", apiPort)
	deadline := time.Now().Add(timeout)

	ctx, cancel := context.WithDeadline(context.Background(), deadline)
	defer cancel()

	client := &http.Client{Timeout: 2 * time.Second}

	attempt := 0
	for {
		attempt++
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
		if err != nil {
			return nil, fmt.Errorf("building /api/self request: %w", err)
		}

		resp, err := client.Do(req)
		if err == nil && resp.StatusCode == http.StatusOK {
			var info selfResponse
			decErr := json.NewDecoder(resp.Body).Decode(&info)
			resp.Body.Close()
			if decErr == nil && info.Pubkey != "" {
				fmt.Fprintf(os.Stderr, "[axl-agent] AXL ready after %d probe(s)\n", attempt)
				return &info, nil
			}
			// Got 200 but bad body — keep trying.
		}
		if resp != nil {
			resp.Body.Close()
		}

		if ctx.Err() != nil {
			return nil, fmt.Errorf("timed out after %s (%d attempts)", timeout, attempt)
		}

		fmt.Fprintf(os.Stderr, "[axl-agent] waiting for AXL (attempt %d)…\n", attempt)
		select {
		case <-ctx.Done():
			return nil, fmt.Errorf("timed out after %s (%d attempts)", timeout, attempt)
		case <-time.After(500 * time.Millisecond):
		}
	}
}
